name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_TOKEN}}
      run: |
        echo "Haciendo login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"

    - name: Build the Docker image
      run: |
        echo "Building image"
        docker build -t joshuadv13/graphql-pipelines:0.0.3 .
        docker build -t joshuadv13/graphql-pipelines:latest .
        echo "Fin de la construccion"

    - name: Push the Docker image
      run: |
        echo "Pushing image to dockerhub"
        docker push joshuadv13/graphql-pipelines:0.0.3
        docker push joshuadv13/graphql-pipelines:latest
        echo "Fin del push"
