name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git semantic version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:"
        minor_pattern: "minor:"
        patch_pattern: "patch:"
        format: "${major}.${minor}.${patch}"
      id: version

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_TOKEN}}
      run: |
        echo "Haciendo login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"

    - name: Build the Docker image
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "Building image $VERSION"
        docker build -t joshuadv13/graphql-pipelines:$VERSION .
        docker build -t joshuadv13/graphql-pipelines:latest .
        echo "Fin de la construccion"

    - name: Push the Docker image
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "Pushing image to dockerhub $VERSION"
        docker push joshuadv13/graphql-pipelines:$VERSION
        docker push joshuadv13/graphql-pipelines:latest
        echo "Fin del push"
